"use client";

import { CalendarClock, Plus, Receipt, TriangleAlert } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { PageHeader, PeriodFilter } from "@/components/app-shell";
import { Field, Modal, StatusBadge } from "@/components/ui";
import { fixedExpenses as initialItems } from "@/lib/demo-data";
import { formatCurrency, normalizePersonName } from "@/lib/format";

export default function FixedExpensesPage() {
  const [items, setItems] = useState(initialItems); const [open, setOpen] = useState(false);
  const total = items.reduce((sum, item) => sum + item.amount, 0);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const amount = Number(data.get("amount")); if (amount <= 0) return toast.error("Informe um valor válido."); setItems((current) => [...current, { id: crypto.randomUUID(), name: String(data.get("name")), category: String(data.get("category")), amount, dueDay: Number(data.get("dueDay")), responsible: normalizePersonName(String(data.get("responsible"))), status: "pending" as const }]); setOpen(false); toast.success("Despesa fixa cadastrada."); }
  return <><PageHeader title="Despesas Fixas" subtitle="Acompanhe contas recorrentes, inclusive as que variam de valor a cada mês." /><div className="toolbar"><PeriodFilter /><button className="primary-button" onClick={() => setOpen(true)}><Plus size={16} /> Adicionar despesa</button></div><section className="subscription-summary"><article><span className="overview-icon blue"><Receipt /></span><div><small>Total do mês</small><strong>{formatCurrency(total)}</strong></div></article><article><span className="overview-icon amber"><CalendarClock /></span><div><small>Pendentes</small><strong>{items.filter((item) => item.status === "pending").length}</strong></div></article><article><span className="overview-icon red"><TriangleAlert /></span><div><small>Em atraso</small><strong>{items.filter((item) => item.status === "overdue").length}</strong></div></article></section><section className="panel list-panel module-section"><div className="panel-heading"><div><h2>Contas recorrentes</h2><p>O valor efetivo pode ser alterado em cada competência</p></div></div><div className="fixed-expense-grid">{items.map((item) => <article key={item.id}><header><span className="overview-icon green"><Receipt /></span><StatusBadge status={item.status} /></header><h3>{item.name}</h3><p>{item.category} · responsável {item.responsible}</p><div><span><small>Valor em agosto</small><strong>{formatCurrency(item.amount)}</strong></span><span><small>Vencimento</small><strong>Dia {item.dueDay}</strong></span></div><button>Editar valor deste mês</button></article>)}</div></section><Modal open={open} onClose={() => setOpen(false)} title="Adicionar despesa fixa" description="O valor informado será uma referência e poderá variar em cada mês."><form className="modal-form" onSubmit={submit}><div className="form-grid two"><Field label="Nome"><input name="name" placeholder="Ex.: Energia" required /></Field><Field label="Categoria"><select name="category"><option>Energia</option><option>Água</option><option>Moradia</option><option>Internet</option><option>Outros</option></select></Field></div><div className="form-grid two"><Field label="Valor de referência"><input name="amount" type="number" min="0.01" step="0.01" required /></Field><Field label="Dia do vencimento"><input name="dueDay" type="number" min="1" max="31" required /></Field></div><Field label="Responsável"><select name="responsible"><option>VICTOR SILVA</option><option>EMILY SILVA</option></select></Field><Field label="Observação"><textarea name="notes" placeholder="Opcional" /></Field><div className="modal-actions"><button type="button" className="ghost-button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button">Salvar despesa</button></div></form></Modal></>;
}
