"use client";
import Link from "next/link";
import { ArrowLeft, Check, KeyRound, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { toast, Toaster } from "sonner";
import { normalizePersonName, normalizeUsername } from "@/lib/format";
import { isValidCpf } from "@/lib/cpf";

export default function RecoveryPage() {
  const router = useRouter(); const [step, setStep] = useState(1); const [name, setName] = useState(""); const [cpf, setCpf] = useState(""); const [action, setAction] = useState<"username" | "password">("password"); const [value, setValue] = useState(""); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false);
  function identify(event: FormEvent) { event.preventDefault(); if (normalizePersonName(name).split(" ").length < 2 || !isValidCpf(cpf)) return toast.error("Confira o nome completo e o CPF."); setStep(2); }
  async function save(event: FormEvent) { event.preventDefault(); const normalized = action === "username" ? normalizeUsername(value) : value; if (action === "password" && normalized.length < 8) return toast.error("A senha deve ter no mínimo 8 caracteres."); setSaving(true); const response = await fetch("/api/auth/recover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName: name, cpf, action, value: normalized }) }); const result = await response.json().catch(() => null); setSaving(false); if (!response.ok) return toast.error(result?.message ?? "Não foi possível atualizar o acesso."); setSaved(true); setTimeout(() => router.push("/entrar"), 2000); }
  return <main className="recovery-page"><Link href="/entrar" className="recovery-back"><ArrowLeft/> Voltar ao login</Link><section className="recovery-card"><div className="recovery-brand"><span className="brand-mark">F</span><strong>Finança Familiar</strong></div>{saved ? <div className="recovery-success"><span><Check/></span><h1>Acesso atualizado!</h1><p>O dado antigo foi substituído no banco. Você voltará ao login em 2 segundos.</p><i className="loading-line"/></div> : <>{step === 1 && <form onSubmit={identify}><span className="recovery-icon"><KeyRound/></span><h1>Recuperar acesso</h1><p>Localize seu cadastro pelo nome completo e CPF.</p><label className="form-field"><span>Nome completo</span><input className="uppercase-input" value={name} onChange={(event) => setName(normalizePersonName(event.target.value))} placeholder="NOME COMPLETO" required/></label><label className="form-field"><span>CPF</span><input value={cpf} onChange={(event) => setCpf(event.target.value)} inputMode="numeric" placeholder="000.000.000-00" required/></label><div className="security-note compact"><ShieldCheck/><p><strong>Seus dados estão protegidos</strong>O CPF é comparado por hash e não é armazenado em texto puro.</p></div><button className="auth-submit">Avançar</button></form>}{step === 2 && <form onSubmit={save}><span className="recovery-icon"><UserRound/></span><h1>O que deseja mudar?</h1><div className="recovery-options"><button type="button" className={action === "username" ? "active" : ""} onClick={() => { setAction("username"); setValue(""); }}><UserRound/><span><strong>Mudar usuário</strong><small>Escolher um novo nome de acesso</small></span><i>{action === "username" && <Check/>}</i></button><button type="button" className={action === "password" ? "active" : ""} onClick={() => { setAction("password"); setValue(""); }}><LockKeyhole/><span><strong>Mudar senha</strong><small>Criar uma nova senha com no mínimo 8 caracteres</small></span><i>{action === "password" && <Check/>}</i></button></div><label className="form-field"><span>{action === "username" ? "Novo usuário" : "Nova senha"}</span><input value={value} onChange={(event) => setValue(action === "username" ? normalizeUsername(event.target.value) : event.target.value)} type={action === "password" ? "password" : "text"} minLength={action === "password" ? 8 : 3} required/></label><div className="modal-actions"><button type="button" className="ghost-button" onClick={() => setStep(1)}>Voltar</button><button disabled={saving} className="auth-submit">{saving ? "Salvando..." : "Salvar alteração"}</button></div></form>}</>}</section><Toaster position="top-right" richColors/></main>;
}
