"use client";
import { Download, FileChartColumn } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { PageHeader, PeriodFilter } from "@/components/app-shell";
import { formatCurrency } from "@/lib/format";
import { useAccount } from "@/lib/use-account";

type Entry = { id: string; type: "income" | "expense"; amount: number; category: string; person: string };
export default function ReportsPage() {
  const { data: account } = useAccount(); const [entries, setEntries] = useState<Entry[]>([]); const [summary, setSummary] = useState({ income: 0, expenses: 0, originated: 0, paid: 0, balance: 0, open: 0 });
  const load = useCallback(async () => { const [response, billsResponse] = await Promise.all([fetch("/api/finance", { cache: "no-store" }), fetch("/api/bills", { cache: "no-store" })]); const [result, billsResult] = await Promise.all([response.json().catch(() => null), billsResponse.json().catch(() => null)]); if (response.ok) { const bills = billsResponse.ok ? billsResult?.bills ?? [] : []; const expenses = Number(result?.summary?.expenses ?? 0); setEntries(result?.entries ?? []); setSummary({ income: Number(result?.summary?.income ?? 0), expenses, originated: expenses, balance: Number(result?.summary?.balance ?? 0), paid: bills.reduce((total: number, bill: { paid: number }) => total + Number(bill.paid ?? 0), 0), open: bills.reduce((total: number, bill: { remaining: number }) => total + Number(bill.remaining ?? 0), 0) }); } }, []);
  useEffect(() => {
    // Atualiza o relatório com os lançamentos persistidos da família.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  const byCategory = useMemo(() => Object.entries(entries.filter((entry) => entry.type === "expense").reduce<Record<string, number>>((result, entry) => ({ ...result, [entry.category]: (result[entry.category] ?? 0) + entry.amount }), {})).sort((a, b) => b[1] - a[1]), [entries]);
  const byPerson = useMemo(() => Object.entries(entries.filter((entry) => entry.type === "expense").reduce<Record<string, number>>((result, entry) => ({ ...result, [entry.person]: (result[entry.person] ?? 0) + entry.amount }), {})).sort((a, b) => b[1] - a[1]), [entries]);
  return <><PageHeader title="Relatórios" subtitle="Competência, pagamentos e caixa sem misturar conceitos."/><div className="report-filters"><PeriodFilter/><select><option>Todas as pessoas</option>{account?.members.map((member) => <option key={member.id}>{member.displayName}</option>)}</select><select><option>Todas as categorias</option>{account?.categories.map((category) => <option key={category.id}>{category.name}</option>)}</select><button className="secondary-button" onClick={() => toast.info(entries.length ? "Exportação será adicionada em uma próxima melhoria." : "Não há dados para exportar.")}><Download size={14}/> Exportar</button></div><section className="report-summary"><article><small>Receitas recebidas</small><strong className="positive-text">{formatCurrency(summary.income)}</strong><span>Movimento de caixa</span></article><article><small>Despesas originadas</small><strong className="negative-text">{formatCurrency(summary.originated)}</strong><span>Base por competência</span></article><article><small>Pagamentos realizados</small><strong className="negative-text">{formatCurrency(summary.paid)}</strong><span>Saídas reais</span></article><article className="accent"><small>Saldo atual de caixa</small><strong>{formatCurrency(summary.balance)}</strong><span>Em aberto: {formatCurrency(summary.open)}</span></article></section><section className="reports-grid"><article className="panel report-chart"><div className="panel-heading"><div><h2>Despesas por competência</h2><p>Valor original gerado no período</p></div></div><div className="source-report">{byCategory.length ? byCategory.map(([name, value]) => <article key={name}><span className="overview-icon blue"><FileChartColumn/></span><div><strong>{name}</strong><small>Categoria</small></div><b>{formatCurrency(value)}</b></article>) : <p>Nenhuma despesa cadastrada.</p>}</div></article><article className="panel report-chart"><div className="panel-heading"><div><h2>Despesas por pessoa</h2><p>Responsabilidade pela compra original</p></div></div><div className="source-report">{byPerson.length ? byPerson.map(([name, value]) => <article key={name}><span className="overview-icon green"><FileChartColumn/></span><div><strong>{name}</strong><small>Integrante</small></div><b>{formatCurrency(value)}</b></article>) : <p>Nenhum gasto cadastrado.</p>}</div></article></section></>;
}
